### ISSUE TITLE
cannotChangeOrganizer 오류

### ISSUE THREAD

**Issue by HyunsDev** [HyunsDev/opize-calendar2notion-syncbot#31]
**Bug Report**

-   Error ID: `343591`
-   Code: `gcal_api_invalid_request`
-   From: `GOOGLE CALENDAR`
-   Level: `ERROR`
-   Func: `GoogleCalendarAssist._updateEvent`

**Data**

```json
{
  "response": {
    "body": {
      "error": {
        "errors": [
          {
            "domain": "calendar",
            "reason": "cannotChangeOrganizer",
            "message": "Cannot change the organizer of attendees copy of the event."
          }
        ],
        "code": 400,
        "message": "Cannot change the organizer of attendees copy of the event."
      }
    },
    "status": 400
  },
  "request": {
    "url": "...",
    "method": "POST",
    "params": {
      "destination": "..."
    }
  }
}
```

**Stack**

```
Error: 구글 캘린더 API 호출 오류 - 400
    at Object.callback (/var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/apiErrorFilterRules.ts:40:23)
    at googleCalendarAPIErrorFilter (/var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/apiErrorFilter.ts:36:34)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/api.decorator.ts:18:21
    at async retry (/var/www/opize-calendar2notion-syncbot/src/utils/retry.ts:7:16)
    at async GoogleCalendarAssistApi.desc.value (/var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/api.decorator.ts:16:25)
    at async GoogleCalendarAssist._updateEvent (/var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/index.ts:111:13)
    at async GoogleCalendarAssist.CUDEvent (/var/www/opize-calendar2notion-syncbot/src/module/worker/assist/googleCalendarAssist/index.ts:102:13)
    at async Worker.syncEvents (/var/www/opize-calendar2notion-syncbot/src/module/worker/Worker.ts:210:13)
    at async Worker.runSteps (/var/www/opize-calendar2notion-syncbot/src/module/worker/Worker.ts:66:13)
```

**Comment by HyunsDev** [comment]
`IGNORE_FORBIDDEN_CANNOT_CHANGE_ORGANIZER` 추가로 해결
