### ISSUE TITLE
cannotChangeOrganizerOfInstance 오류

### ISSUE THREAD

**Issue by HyunsDev** [HyunsDev/opize-calendar2notion-syncbot#33]
**Bug Report**

-   Error ID: `343716`
-   Code: `gcal_api_invalid_request`
-   From: `GOOGLE CALENDAR`
-   Level: `ERROR`
-   Func: `GoogleCalendarAssist._updateEvent()`

**Data**

```json
{
  "response": {
    "body": {
      "error": {
        "errors": [
          {
            "domain": "calendar",
            "reason": "cannotChangeOrganizerOfInstance",
            "message": "Cannot change the organizer of an instance."
          }
        ],
        "code": 400,
        "message": "Cannot change the organizer of an instance."
      }
    },
    "status": 400
  },
  "request": {
    "url": "...",
    "method": "POST",
    "params": {
      "destination": "..."
    }
  }
}
```

**Stack**

```
Error: 구글 캘린더 API 호출 오류 - 400
    at Object.callback (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/apiErrorFilterRules.js:28:19)
    at googleCalendarAPIErrorFilter (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/apiErrorFilter.js:18:34)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/api.decorator.js:12:62
    at async retry (/var/www/opize-calendar2notion-syncbot/dist/src/utils/retry.js:6:16)
    at async desc.value (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/api.decorator.js:12:25)
    at async GoogleCalendarAssist._updateEvent (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/index.js:73:13)
    at async GoogleCalendarAssist.CUDEvent (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/assist/googleCalendarAssist/index.js:66:13)
    at async Worker.syncEvents (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/Worker.js:145:13)
    at async Worker.runSteps (/var/www/opize-calendar2notion-syncbot/dist/src/module/worker/Worker.js:43:13)
```

**Comment by HyunsDev** [comment]
해결방법 -> 무시
